version: '2'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    volumes:
      - ./keycloak_themes:/opt/keycloak/themes
      - ./plugins/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar
      - ./risk-base/target/risk-base-1.0.0.jar:/opt/keycloak/providers/risk-base-1.0.0.jar
      - ./risk-base/target/risk-base-1.0.0-jar-with-dependencies.jar:/opt/keycloak/providers/risk-base-1.0.0-jar-with-dependencies.jar
      - ./user-information/target/user-information-1.0.0.jar:/opt/keycloak/providers/user-information-1.0.0.jar
      - ./user-information/target/user-information-1.0.0-jar-with-dependencies.jar:/opt/keycloak/providers/user-information-1.0.0-jar-with-dependencies.jar
      - ./sync-user/target/sync-user-1.0.0.jar:/opt/keycloak/providers/sync-user-1.0.0.jar
      - ./sync-user/target/sync-user-1.0.0-jar-with-dependencies.jar:/opt/keycloak/providers/sync-user-1.0.0-jar-with-dependencies.jar
      - ./plugins/email:/opt/keycloak/themes/base/email
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak?user=postgres&password=postgres
      - KC_HOSTNAME=keycloak.openlearnhub.io.vn
    command:
      - start-dev
    ports:
      - "7080:8080"
    container_name: keycloak
    networks:
      - shop-sport-micro

networks:
  shop-sport-micro:
    external: true

volumes:
  postgres_data: # Định nghĩa volume ngoài
