version: '2'

services:
  postgres:
    image: postgres:15
    container_name: postgresql
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop-sport-micro
    # Không có ports mapping - chỉ accessible từ các container khác trong cùng network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    volumes:
      - ./keycloak_themes:/opt/keycloak/themes
      - ./plugins/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar
      - ./sync-user/target/sync-user-1.0.0-jar-with-dependencies.jar:/opt/keycloak/providers/sync-user-1.0.0-jar-with-dependencies.jar
      - ./plugins/email:/opt/keycloak/themes/base/email
    environment:
      - KEYCLOAK_BOOTSTRAP_ADMIN=admin
      - KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD=R9t!2bXz@5zQ#4kF
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresql/keycloak?user=postgres&password=postgres
      - KC_HOSTNAME=keycloak.gcp.openlearnhub.io.vn
      - PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
    command:
      - start-dev
    ports:
      - "7080:8080"
    container_name: keycloak
    networks:
      - shop-sport-micro
    depends_on:
      - postgres

networks:
  shop-sport-micro:
    external: true

volumes:
  postgres_data: