version: '2'

services:
  # PostgreSQL Master
  dbzpostgresql:
    image: quay.io/debezium/postgres:15
    command:
      -c work_mem=512MB
      -c maintenance_work_mem=512MB
      -c max_wal_size=2GB
    container_name: dbzpostgresql
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data # Thêm volume cho PostgreSQL
    networks:
      - shop-sport-micro

  # KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    volumes:
      - ./keycloak_themes:/opt/keycloak/themes
      - ./plugins/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar
      - ./plugins/email:/opt/keycloak/themes/base/email
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://dbzpostgresql/keycloak?user=postgres&password=postgres
    command:
      - start-dev
    ports:
      - "7080:8080"
    container_name: keycloak
    depends_on:
      - dbzpostgresql
    networks:
      - shop-sport-micro

networks:
  shop-sport-micro:
    external: true

volumes:
  postgres_data: # Định nghĩa volume ngoài
